// A VARIÁVEL VAR É UMA VARIÁVEL DE ESCOPO GLOBAL, QUE ACEITA MAIS DE UMA DECLARAÇÃO COM O MESMO IDENTIFICADOR.

// ENQUANTO A VARIÁVEL LET É UMA VARIÁVEL DE ESCOPO LOCAL, QUE ACEITA UMA UNICA DECLARALÇÃO DENTRO DO ESCOPO.

// OBS: AMBAS AS VARIÁVEIS ACEITAM ALTERAÇÕES NO VALOR ATRIBUÍDO À VARIÁVEL
let banda;
banda = "Mettalica";

banda = "Nirvana";