//  A VARIÁVEL CONST DEVERÁ SER DECLARADA E ATRIBUÍDA  NA MESMA INSTRUÇÃO DE CÓDIGO. O VALOR DEVERÁ SER CONSTANTE, OU SEJA, NÃO PODE SER ATRIBUÍDO UM NOVO VALOR AO DECORRER DO CÓDIGO.

// ASSIM COMO A VARIÁVEL LET, A VARIÁVEL CONST É DE ESPAÇO LOCAL

const vocalista = "Freddie Mercury";

console.log(vocalista);
